server:
  port: 8080

---
spring:
  profiles: dev

---
spring:
  profiles: testing
  datasource:
    schema: classpath:db/schema-h2.sql
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:px
    username: root


logging:
  level:
    xyz:
      bbear: debug

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: localhost
      port: 6379

---
spring:
  profiles: staging

---
spring:
  profiles: production