server:
  port: 8080
mybatis:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    property-naming-strategy: SNAKE_CASE
  data:
    mybatis:
      repositories:
        snowflake:
          enabled: true
          datacenter-id: 0
          worker-id: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://' + serviceId"
    kubernetes:
      discovery:
        filter: "metadata.labels['discovery']"

service:
  discovery: true

---
spring:
  profiles: dev

---
spring:
  profiles: testing
  datasource:
#    schema: classpath:db/init_table.sql
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:db/schema-h2.sql'\\;RUNSCRIPT FROM 'classpath:db/data-h2.sql'
    username: root

logging:
  level:
    xyz:
      bbear: debug

---
spring:
  profiles: staging

---
spring:
  profiles: production